### ISSUE TITLE
Add support for hg.mozilla.org

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#5]
We need to implement something similar to DXR and Searchfox (the code is in dxr.js, searchfox.js, dxr-common.js), but for hg.mozilla.org.
Basically, we want to show a coverage overlay on top of the source files in hg.mozilla.org (e.g. on top of https://hg.mozilla.org/mozilla-central/file/tip/widget/gtk/nsWindow.cpp).

**Comment by DGRamya** [comment]
Hello @marco-c,
In order to complete outreachy application, I need to submit one code commit. Could you please provide description for this bug, So that I can work on this "good-first-bug" issue and commit code.

**Comment by marco-c** [comment]
Hello @DGRamya, in order to fix this, we need to implement something similar to DXR and Searchfox (the code is in dxr.js, searchfox.js, dxr-common.js), but for hg.mozilla.org.
Basically, we want to show a coverage overlay on top of the source files in hg.mozilla.org (e.g. on top of https://hg.mozilla.org/mozilla-central/file/tip/widget/gtk/nsWindow.cpp).

Do you already have some experience in writing WebExtensions? If you don't, maybe it's better to start with an issue from one of the other repos.

**Comment by DGRamya** [comment]
@marco-c, No I am not experienced in web-extensions. I have experience in Java, JavaScript, Shell Scripting. Any suggestions for goot-first-bug will be helpful.

**Comment by marco-c** [comment]
@DGRamya you can find a good first bug from one of the repositories mentioned in the Outreachy project page. Let me know via email if you can't find any.

**Comment by divyabaid16** [comment]
@marco-c  I had added the extension locally by adding the unedited mainfest.json file, it was working for the Bugzilla site but not for [drx](https://dxr.mozilla.org/mozilla-central/source/tools/code-coverage/CodeCoverageHandler.cpp) and [searchfox](https://searchfox.org/mozilla-central/source/tools/code-coverage/CodeCoverageHandler.cpp). Since it was not working for both of these sites, I am unable to test it for hg.mozilla.org. Can you please tell me why is the local extension not working with dxr and searchfox if [this](https://addons.mozilla.org/en-US/firefox/addon/gecko-code-coverage/) is working ?

**Comment by marco-c** [comment]
Have you built the addon before loading it with "npm run build"?
Note in Searchfox there's currently a bug that is preventing it from working (#29).

> Since it was not working for both of these sites, I am unable to test it for hg.mozilla.org.

hg.mozilla.org is actually independent from DXR and Searchfox, so you can test the addon on hg.mozilla.org anyways.

**Comment by divyabaid16** [comment]
I have built the addon before loading it with "npm run build" 
But still, I am unable to test it.

**Comment by divyabaid16** [comment]
I have built the addon before loading it with "npm run build" 
But still, I am unable to test it.

**Comment by marco-c** [comment]
Unfortunately I have no idea what else could be causing your local setup not to work.
